### ISSUE TITLE
Request to fix invalid file name exception during archiving

### ISSUE THREAD

**Issue by AtagoDaisuki** [bryantbhowell/Behold--Emailer#3]
In BeholdEmailer.cs, line 166:

_generate_email_from_view_ function cannot archive file names properly if username (impersonated) includes a domain prefix (e.g. domain\username). This causes a fatal exception which stops the program, because a valid file name cannot contain slash. I think many companies have different domains, and their usernames, without proper domain prefix, cannot be recognized by the Tableau server.

**Log:**

System.IO.DirectoryNotFoundException: Could not find a part of the path 'TEST - vch.ca\AC3073_SA - 2018_05_23T19_16_01.pdf'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Behold_Emailer.BeholdEmailer.generate_email_from_view(String email_from_user, String[] email_to, String[] email_cc, String[] email_bcc, String email_subject, String email_template_name, String view_user, String view_location, String email_content_type, Dictionary`2 view_filter_dictionary, Watermarker watermark)
   at Behold_Emailer.Configure.send_email(String schedule_name)
   at Behold_Emailer.Configure.send_test_email(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by AtagoDaisuki** [comment]
Hi bryantbhowell,

Since I was able to compile the exact application from source code, I forked this app and made the changes requested above. I'm new to using Git (though not new to Git), and will continue to make changes in my fork until my organization can use this application.

Thank you!
